server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://111.230.132.23:3306/goods?useSSL=false
    username: root
    password: 147852369Abc
    driverClassName: com.mysql.jdbc.Driver
    smax-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
